import streamlit as st
import pandas as pd
import os
from firm import run_trading_firm

# 1. Page Configuration & Styling
st.set_page_config(page_title="AI Trading Desk", page_icon="📈", layout="wide")
st.title("📈 AI Quantitative Research Desk")
st.write("Welcome to your autonomous trading firm. Enter an Indian stock ticker to dispatch your AI agents.")

# Use a two-column layout for the input panel
col1, col2 = st.columns([2, 1])
with col1:
    ticker_input = st.text_input("Enter NSE Ticker:", "RELIANCE.NS")
with col2:
    st.write("##") # Visual spacing
    dispatch_clicked = st.button("Dispatch AI Team", use_container_width=True)

# 2. Execution Logic
if dispatch_clicked:
    with st.spinner(f"CEO is coordinating research for {ticker_input}..."):
        
        # Trigger the CrewAI engine
        final_report = run_trading_firm(ticker_input)
        
        st.success("Research Complete!")
        
        # Layout splitting: Left side for the AI summary, Right side for raw data visuals
        left_col, right_col = st.columns(2)
        
        with left_col:
            st.subheader("🤖 Executive Summary")
            st.info(final_report.raw)
            
        with right_col:
            st.subheader("📊 Quantitative Data Desk")
            
            # Clean up the input string to find the saved file name
            clean_ticker = ticker_input.strip().upper()
            if not clean_ticker.endswith('.NS') and not clean_ticker.endswith('.BO'):
                clean_ticker = f"{clean_ticker}.NS"
                
            file_path = f"data/{clean_ticker}_data.csv"
            
            # If the CSV exists, let's turn it into a gorgeous dashboard panel
            if os.path.exists(file_path):
                # Read the saved CSV data
                df = pd.read_csv(file_path)
                
                # Dynamic performance metrics
                if 'Close' in df.columns:
                    # Flatten out columns if pandas read multi-headers
                    df.columns = [col[0] if isinstance(col, tuple) else col for col in df.columns]
                    
                    # --- THE DATA CLEANER FIX ---
                    # Force the 'Close' column to be pure numbers. Any text becomes 'NaN' (blank).
                    df['Close'] = pd.to_numeric(df['Close'], errors='coerce')
                    # Drop the blank rows
                    df = df.dropna(subset=['Close'])
                    # ----------------------------

                    latest_price = float(df['Close'].iloc[-1])
                    start_price = float(df['Close'].iloc[0])
                    pct_change = ((latest_price - start_price) / start_price) * 100
                    
                    # Display metrics row
                    m1, m2 = st.columns(2)
                    m1.metric("Latest Close", f"INR {latest_price:.2f}")
                    m2.metric("6mo Trend Performance", f"{pct_change:+.2f}%", delta_color="normal")
                    
                    # Draw a clean, interactive stock price line chart
                    st.write("**Historical Price Action (Last 6 Months)**")
                    st.line_chart(df['Close'])
                
                # Provide a dropdown accordion to preview the raw data table
                with st.expander("👁️ Preview Raw CSV Dataset"):
                    st.dataframe(df, use_container_width=True)
            else:
                st.warning("Data file generated by the analyst tool could not be located for visualization.")